### ISSUE TITLE
Welcome screen

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/app-integrator-ui#3]
Needs a welcome screen with message to:
- Click one of the items in the header or
- Configure the application if the header is empty (no services configured)

**Comment by madnificent** [comment]
We can add a big BDE logo in there and show configuration help when no
links are available.

That should be sufficient, right?

**Comment by earthquakesan** [comment]
I think, when there is a configuration some kind of help is needed.
Like button should blink "click me" or just a big "click the toolbar" over the screen.

**Comment by madnificent** [comment]
Agreed
